githooks/pre-commit: be less mysterious about failures

diff --git a/githooks/pre-commit b/githooks/pre-commit
--- a/githooks/pre-commit
+++ b/githooks/pre-commit
@@ -13,21 +13,10 @@ fi
 exec 1>&2
 
 # If there are whitespace errors, print the offending file names and fail.
-git diff-index --check --cached $against --
+git diff-index --check --cached $against -- || ( echo "found whitespace errors" ; exit 1 )
 
 gopkgs="$(go list ./... | grep -v 'vendor|third_party')"
 
-gofmt="$(gofmt -d .)"
-if [ -n "${gofmt}" ]
-then
-	echo -e "${gofmt}"
-	false
-fi
+gofmt -d . 2>&1 || ( echo "gofmt found diffs" ; exit 1 )
 
-# TODO: renable test-on-pre-commit when Go tests are passing again.
-gotest="$(go test -timeout 30s -short ${gopkgs})"
-if [ $? -ne 0 ]
-then
-	echo -e "${gotest}"
-	false
-fi
+go test -timeout 30s -short ${gopkgs} || ( echo "go test failed" ; exit 1 )
